package core;

import java.util.InputMismatchException;
import java.util.Scanner;

//try,catch,finally,throw,throws
class Divide{ //A
	public void division() throws ArithmeticException,InputMismatchException{
		Scanner sc = new Scanner(System.in);
		System.out.println("enter a = ");
		int a = sc.nextInt();
		System.out.println("enter b = ");
		int b = sc.nextInt();
		int c = a / b;
		System.out.println(c);
	}
}
public class P019_Exception { //B
	public static void main(String[] args) {
		try {
			Divide d = new Divide();
			d.division();
		} catch (Exception e) {
			// TODO: handle exception
		}
		
		
		
		
		
		
//		try {
//			Scanner sc = new Scanner(System.in);
//			System.out.println("enter a = ");
//			int a = sc.nextInt();
//			System.out.println("enter b = ");
//			int b = sc.nextInt();
//			int c = a / b;
//			System.out.println(c);
//			System.exit(23);
//		} catch (ArithmeticException e) {
//			System.out.println("number cannot divide by < 0");
//		} catch (InputMismatchException e) {
//			System.out.println("number cannot divide by string");
//		} catch (Exception e) {
//			e.printStackTrace();
//		} finally {
//			System.out.println("this will exectues everytime");
//		}
	}
}
